version: '3'

services:
  back:
    build: .
    restart: unless-stopped
    container_name: back
    ports:
      - 8080:80
  db:
    image: mysql
    restart: unless-stopped
    container_name: db
    env_file:
      - .env
    volumes:
      - mysql_db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysql_db: